package ru.silvestrov.timetracker.data;

import org.hibernate.dialect.DerbyDialect;

/**
 * Created by Silvestrov Iliya.
 * Date: Jul 14, 2008
 * Time: 2:13:07 AM
 */
public class GeneratedByDefaultDerbyDialect extends DerbyDialect {
    public String getIdentityColumnString() {
        return "not null generated by default as identity (START WITH 50)";
    }
}
